### ISSUE TITLE
questions about the first draft

### ISSUE THREAD

**Issue by caridy** [zenparsing/node-default-module-proposal#4]
### 1

> 1. There is no change to the behavior of `require`. It cannot be used to import ES6 modules.

this seems misleading since you're also proposing a way to support requiring any ES standard module, if the author takes the right precautionary steps (folder structure with `index.js`).
### 2

> The word "default" has a special, and similar meaning in ES6 modules.

This is confusing, considering that you're not going to get the default export, but the namespace exotic object instead, maybe we should call it something else, ns.js or namespace.js or mod.js, etc.
### 3

> require.import

I like `require.import`, it should consider an sync version of the imperative `import()` call:

e.g.:

```
const m = await import('./src/foo.js');
const m = require.import('./src/foo.js');
```

_clearly that is still TBD :), but we are working on it_
### 4

Part of the goal, marked as a constrain in the dot-js proposal was:

> Agnostic Usage: It must be possible for applications that use a new-world package to import modules without having to know whether the module uses CommonJS modules or standard JavaScript modules. We should also try to allow all existing usage patterns to remain agnostic to the kind of module they are importing and minimize disruption to existing patterns.

We think that a new version of the pkg should just work, and a semver bump should not be required. This proposal seems to solve this by requiring to create a folder structure with index.js on them, which seems reasonable, and probably equivalent in complexity to the poly-package proposal from dot-js
### 5

> `default.js` in the root folder vs a mark in `pkg.json`

IMO, this will buy us little, considering that ~85% of the pkgs in npm are using "main".
### 6

> A Modest Proposal

I still think this is more complex than package.json, especially for the future. You have to learn a bunch of rules as a pkg author and as a pkg consumer.

**Comment by zenparsing** [comment]
### 1

> this seems misleading since you're also proposing a way to support requiring any ES standard module, if the author takes the right precautionary steps (folder structure with index.js).

But technically true, since from the point of view of the "requirer" it's in fact a CJS module.

### 2 

> This is confusing, considering that you're not going to get the default export, but the namespace exotic object instead, maybe we should call it something else, ns.js or namespace.js or mod.js, etc.

Point taken; it's not exactly analogous to default exports.  Although I think the similarity of concepts is helpful, in a way.  The default export is what you get from a module when you don't specify an export name, and the default module is what you get when you don't specify a file name within a folder/package.  I'm not convinced yet that it's confusing.

### 4

I think that this part of the constraint:

> We should also try to allow all existing usage patterns to remain agnostic to the kind of module they are importing and minimize disruption to existing patterns.

is problematic because it forces us into a complete interoperability solution.  That might be the best option, but I think it's at least helpful to explore solutions where we sacrifice some of these goals slightly.  A little disruption might be fine  : )

### 5

> IMO, this will buy us little, considering that ~85% of the pkgs in npm are using "main".

IMO, binding resolution logic to reading a package manifest JSON file is insane, no matter how many packages do it.  That said, I realize that I'm being contrarian.  We could probably modify this proposal so that it looks at package.json as well, but I haven't thought through the implications.

### 6

> I still think this is more complex than package.json, especially for the future. You have to learn a bunch of rules as a pkg author and as a pkg consumer.

Really?  In the far future (when all your target Node versions support modules) you need only one rule: "default.js for folder entry point".  This is actually more simple that the current CJS setup, where you have to take package.json files into account.

**Comment by zenparsing** [comment]
Closing out old threads
